# Use an official Node.js LTS (Long Term Support) image as the base image
FROM node:18.12.1-alpine

# Set the working directory
WORKDIR /app



# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm cache clean --force

RUN npm install --legacy-peer-deps

    
# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to start the development server
CMD ["npm", "run", "start"]

