version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: react-app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./src:/app/src

